realms/modules/wiki/views.py
from __future__ import absolute_import

import collections
import itertools
import sys
from datetime import datetime

from flask import abort, g, render_template, request, redirect, Blueprint, flash, url_for, current_app, make_response
from werkzeug.contrib.atom import AtomFeed
from flask_login import login_required, current_user

from realms.version import __version__
from realms.lib.util import to_canonical, remove_ext, gravatar_url, is_markdown
from .models import PageNotFound

blueprint = Blueprint('wiki', __name__, template_folder='templates',
                      static_folder='static', static_url_path='/static/wiki')


@blueprint.route("/_commit/<sha>/<path:name>")
def commit(name, sha):
    if current_app.config.get('PRIVATE_WIKI') and current_user.is_anonymous:
        return current_app.login_manager.unauthorized()

    cname = to_canonical(name)

    data = g.current_wiki.get_page(cname, sha=sha.decode())

    if not data:
        abort(404)

    partials = _partials(data.imports, sha=sha.decode())

    return render_template('wiki/page.html', name=name, page=data, commit=sha, partials=partials)


@blueprint.route(r"/_compare/<path:name>/<regex('\w+'):fsha><regex('\.{2,3}'):dots><regex('\w+'):lsha>")
def compare(name, fsha, dots, lsha):
    if current_app.config.get('PRIVATE_WIKI') and current_user.is_anonymous:
        return current_app.login_manager.unauthorized()

    diff = g.current_wiki.get_page(name, sha=lsha).compare(fsha)
    return render_template('wiki/compare.html',
                           name=name, diff=diff, old=fsha, new=lsha)


@blueprint.route("/_revert", methods=['POST'])
@login_required
def revert():
    cname = to_canonical(request.form.get('name'))
    commit = request.form.get('commit')
    message = request.form.get('message', "Reverting %s" % cname)

    if not current_app.config.get('ALLOW_ANON') and current_user.is_anonymous:
        return dict(error=True, message="Anonymous posting not allowed"), 403

    if cname in current_app.config.get('WIKI_LOCKED_PAGES'):
        return dict(error=True, message="Page is locked"), 403

    try:
        sha = g.current_wiki.get_page(cname).revert(commit,
                                                    message=message,
                                                    username=current_user.username,
                                                    email=current_user.email)
    except PageNotFound as e:
        return dict(error=True, message=e.message), 404

    if sha:
        flash("Page reverted")

    return dict(sha=sha.decode())


@blueprint.route("/_history/<path:name>")
def history(name):
    if current_app.config.get('PRIVATE_WIKI') and current_user.is_anonymous:
        return current_app.login_manager.unauthorized()
    return render_template('wiki/history.html', name=name)


@blueprint.route("/_feed/<path:name>")
def feed(name):
    if current_app.config.get('PRIVATE_WIKI') and current_user.is_anonymous:
        return current_app.login_manager.unauthorized()
    cname = to_canonical(name)
    wiki_name = current_app.config['SITE_TITLE']
    start = 0
    length = int(request.args.get('length', 20))

    the_feed = AtomFeed(
        title="{} - Recent changes for page '{}'".format(wiki_name, cname),
        url=url_for('wiki.page', name=cname, _external=True),
        id="{}_pagefeed_{}".format(to_canonical(wiki_name), cname),
        feed_url=url_for('wiki.feed', name=cname, _external=True),
        generator=("Realms wiki", 'https://github.com/scragg0x/realms-wiki', __version__)
    )

    page = g.current_wiki.get_page(cname)
    items = list(itertools.islice(page.history, start, start + length))  # type: list[dict]

    for item in items:
        the_feed.add(
            title="Commit '{}'".format(item['sha']),
            content=item['message'],
            url=url_for('wiki.commit', name=name, sha=item['sha'], _external=True),
            id="{}/{}".format(item['sha'], cname),
            author=item['author'],
            updated=datetime.fromtimestamp(item['time'])
        )

    response = make_response((the_feed.to_string(), {'Content-type': 'application/atom+xml; charset=utf-8'}))
    response.add_etag()
    return response.make_conditional(request)


@blueprint.route("/_history_data/<path:name>")
def history_data(name):
    """Ajax provider for paginated history data."""
    if current_app.config.get('PRIVATE_WIKI') and current_user.is_anonymous:
        return current_app.login_manager.unauthorized()
    draw = int(request.args.get('draw', 0))
    start = int(request.args.get('start', 0))
    length = int(request.args.get('length', 10))
    page = g.current_wiki.get_page(name)
    items = list(itertools.islice(page.history, start, start + length))     # type: list[dict]
    for item in items:
        item['gravatar'] = gravatar_url(item['author_email'])
        item['DT_RowId'] = item['sha']
        date = datetime.fromtimestamp(item['time'])
        item['date'] = date.strftime(current_app.config.get('DATETIME_FORMAT', '%b %d, %Y %I:%M %p'))
        item['link'] = url_for('.commit', name=name, sha=item['sha'])
    total_records, hist_complete = page.history_cache
    if not hist_complete:
        # Force datatables to fetch more data when it gets to the end
        total_records += 1
    return {
        'draw': draw,
        'recordsTotal': total_records,
        'recordsFiltered': total_records,
        'data': items,
        'fully_loaded': hist_complete
    }


@blueprint.route("/_edit/<path:name>")
@login_required
def edit(name):
    cname = to_canonical(name)
    page = g.current_wiki.get_page(cname)

    if not page:
        # Page doesn't exist
        return redirect(url_for('wiki.create', name=cname))

    g.assets['js'].append('editor.js')
    return render_template('wiki/edit.html',
                           name=cname,
                           content=page.data.decode(),
                           # TODO: Remove this? See #148
                           info=next(page.history),
                           sha=page.sha)


def _partials(imports, sha='HEAD'):
    page_queue = collections.deque(imports)
    partials = collections.OrderedDict()
    while page_queue:
        page_name = page_queue.popleft()
        if page_name in partials:
            continue
        page = g.current_wiki.get_page(page_name, sha=sha.decode())
        try:
            partials[page_name] = page.data
        except KeyError:
            partials[page_name] = "`Error importing wiki page '{0}'`".format(page_name)
            continue
        page_queue.extend(page.imports)
    # We want to retain the order (and reverse it) so that combining metadata from the imports works
    # nested list for python >3.5 compatibility
    return list(reversed(list(partials.items())))


@blueprint.route("/_partials")
def partials():
    if current_app.config.get('PRIVATE_WIKI') and current_user.is_anonymous:
        return current_app.login_manager.unauthorized()
    return {'partials': _partials(request.args.getlist('imports[]'))}


@blueprint.route("/_create/", defaults={'name': None})
@blueprint.route("/_create/<path:name>")
@login_required
def create(name):
    cname = to_canonical(name) if name else ""
    if cname and g.current_wiki.get_page(cname):
        # Page exists, edit instead
        return redirect(url_for('wiki.edit', name=cname))

    g.assets['js'].append('editor.js')
    return render_template('wiki/edit.html',
                           name=cname,
                           content="",
                           info={})


def _get_subdir(path, depth):
    parts = path.split('/', depth)
    if len(parts) > depth:
        return parts[-2]


def _tree_index(items, path=""):
    depth = len(path.split("/"))
    items = sorted(items, key=lambda x: x['name'])
    for subdir, items in itertools.groupby(items, key=lambda x: _get_subdir(x['name'], depth)):
        if not subdir:
            for item in items:
                yield dict(item, dir=False)
        else:
            size = 0
            ctime = sys.maxint
            mtime = 0
            for item in items:
                size += item['size']
                ctime = min(item['ctime'], ctime)
                mtime = max(item['mtime'], mtime)
            yield dict(name=path + subdir + "/",
                       mtime=mtime,
                       ctime=ctime,
                       size=size,
                       dir=True)


@blueprint.route("/_index", defaults={"path": ""})
@blueprint.route("/_index/<path:path>")
def index(path):
    if current_app.config.get('PRIVATE_WIKI') and current_user.is_anonymous:
        return current_app.login_manager.unauthorized()

    items = g.current_wiki.get_index()
    if path:
        path = to_canonical(path) + "/"
        items = filter(lambda x: x['name'].startswith(path), items)
    if not request.args.get('flat', '').lower() in ['yes', '1', 'true']:
        items = _tree_index(items, path=path)

    return render_template('wiki/index.html', index=items, path=path)


@blueprint.route("/<path:name>", methods=['POST', 'PUT', 'DELETE'])
@login_required
def page_write(name):
    cname = to_canonical(name)

    if not cname:
        return dict(error=True, message="Invalid name")

    if not current_app.config.get('ALLOW_ANON') and current_user.is_anonymous:
        return dict(error=True, message="Anonymous posting not allowed"), 403

    if request.method == 'POST':
        # Create
        if cname in current_app.config.get('WIKI_LOCKED_PAGES'):
            return dict(error=True, message="Page is locked"), 403

        sha = g.current_wiki.get_page(cname).write(request.form['content'],
                                                   message=request.form['message'],
                                                   username=current_user.username,
                                                   email=current_user.email)

    elif request.method == 'PUT':

realms/modules/wiki/templates/wiki/compare.html
{% extends 'layout.html' %}
{% block body %}

  <h2>History for <strong>{{ name }}</strong></h2>
  <div class="pull-right">
    <a href="{{ url_for('wiki.commit', name=name, sha=old) }}" class="btn btn-default btn-sm">View Old</a>
    <a href="{{ url_for('wiki.commit', name=name, sha=new) }}" class="btn btn-info btn-sm">View New</a>
  </div>
  <p>
    <a class="btn btn-default btn-sm" href="{{ url_for('wiki.history', name=name) }}">Back to History</a>
  </p>
  {{ diff|safe }}
  <p>
    <a class="btn btn-default btn-sm" href="{{ url_for('wiki.history', name=name) }}">Back to History</a>
  </p>
{% endblock %}

realms/modules/wiki/templates/wiki/edit.html
{% extends 'layout.html' %}
{% block js %}
  <script>
    var Commit = {};
    Commit.info = {{ info|tojson }};

    var PAGE_NAME = '{{ name }}';
    var csrf_token = "{{ csrf_token() }}";
  </script>
  <script src="{{ url_for('wiki.static', filename='js/editor.js') }}"></script>

  {% if config.get('COLLABORATION') %}
    <script src="{{ url_for('wiki.static', filename='js/collaboration/main.js') }}"></script>
  {% endif %}

  {% if config.get('COLLABORATION') == 'firepad' %}
    <script>
      Config['FIREBASE_HOSTNAME'] = {{ config.get('FIREBASE_HOSTNAME')|tojson }};
    </script>
    <script src="https://cdn.firebase.com/js/client/1.0.17/firebase.js"></script>
    <script src="https://cdn.firebase.com/libs/firepad/1.0.0/firepad.min.js"></script>
    <script src="{{ url_for('wiki.static', filename='js/collaboration/firepad.js') }}"></script>
  {% endif %}

  {% if config.get('COLLABORATION') == 'togetherjs' %}
    <script src="{{ url_for('wiki.static', filename='js/collaboration/togetherjs.js') }}"></script>
    <script src="https://togetherjs.com/togetherjs-min.js"></script>
  {% endif %}
{% endblock %}

{% block body %}
  <div id="app-wrap">
    <div id="app-controls" class="row">
      <div class="col-xs-4 col-md-3">
        <input id="page-name" type="text" class="form-control input-sm" name="name"
               placeholder="Name" value="{{- name -}}" />
      </div>
      <div class="col-xs-4 col-md-3">
        <input id="page-message" type="text" class="form-control input-sm" name="page-message"
               placeholder="Comment" value="" />
      </div>

      <div class="col-md-6 col-xs-4 text-right">

        {% if config.get('COLLABORATION') %}
          <div class="btn-group">
            <button style='display:none' class="btn btn-danger btn-sm" id="end-collaboration">
              <i class="fa fa-comments-o"></i>
              <span class="hidden-xs">End Collaboration</span>
            </button>
          </div>
          <div class="btn-group">
            <button style='display:none' class="btn btn-default btn-sm" id="loading-collaboration" type="button">
              <i class="fa fa-cog fa-spin"></i>
              <span class="hidden-xs">Loading</span>
            </button>
          </div>
        {% endif %}

        <div class="dropdown btn-group">
          <button class="btn btn-default btn-sm dropdown-toggle" type="button" id="editor-actions"
                  data-toggle="dropdown" title="Actions">
            <i class="fa fa-cog"></i>
            <span class="hidden-xs hidden-sm">Actions <i class="fa fa-caret-down"></i></span>
          </button>

          <ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="editor-actions">
            {% if config.get('COLLABORATION') %}
              <li role="presentation">
                <a role="menuitem" tabindex="-1" href="#" id="start-collaboration">Collaborate</a>
              </li>
              <li role="presentation" class="divider"></li>
            {% endif %}
            <li role="presentation">
              <a role="menuitem" tabindex="-1" href="#" id="discard-draft-btn">Delete Draft</a>
            </li>
            <li role="presentation">
              <a role="menuitem" tabindex="-1" href="#" id="delete-page-btn">Delete Page</a>
            </li>
          </ul>
        </div>

        <div class="dropdown btn-group">
          <button id="theme-list-btn" type="button" class="dropdown-toggle btn btn-default btn-sm"
                  data-toggle="dropdown" title="Change Theme">
            <i class="fa fa-paint-brush"></i>
            <span class="hidden-xs hidden-sm">Theme <i class="fa fa-caret-down"></i></span>
          </button>
          <ul id="theme-list" class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="theme-list">
            <li><a tabindex="-1" href="#" data-value="chrome" >Chrome</a></li>
            <li><a tabindex="-1" href="#" data-value="clouds" >Clouds</a></li>
            <li><a tabindex="-1" href="#" data-value="clouds_midnight" >Clouds Midnight</a></li>
            <li><a tabindex="-1" href="#" data-value="cobalt" >Cobalt</a></li>
            <li><a tabindex="-1" href="#" data-value="crimson_editor" >Crimson Editor</a></li>
            <li><a tabindex="-1" href="#" data-value="dawn" class="selected">Dawn</a></li>
            <li><a tabindex="-1" href="#" data-value="dreamweaver" >Dreamweaver</a></li>
            <li><a tabindex="-1" href="#" data-value="eclipse" >Eclipse</a></li>
            <li><a tabindex="-1" href="#" data-value="idle_fingers" >idleFingers</a></li>
            <li><a tabindex="-1" href="#" data-value="kr_theme" >krTheme</a></li>
            <li><a tabindex="-1" href="#" data-value="merbivore" >Merbivore</a></li>
            <li><a tabindex="-1" href="#" data-value="merbivore_soft" >Merbivore Soft</a></li>
            <li><a tabindex="-1" href="#" data-value="mono_industrial" >Mono Industrial</a></li>
            <li><a tabindex="-1" href="#" data-value="monokai" >Monokai</a></li>
            <li><a tabindex="-1" href="#" data-value="pastel_on_dark">Pastel on Dark</a></li>
            <li><a tabindex="-1" href="#" data-value="solarized_dark" >Solarized Dark</a></li>
            <li><a tabindex="-1" href="#" data-value="solarized_light" >Solarized Light</a></li>
            <li><a tabindex="-1" href="#" data-value="textmate" >TextMate</a></li>
            <li><a tabindex="-1" href="#" data-value="tomorrow" >Tomorrow</a></li>
            <li><a tabindex="-1" href="#" data-value="tomorrow_night">Tomorrow Night</a></li>
            <li><a tabindex="-1" href="#" data-value="tomorrow_night_blue" >Tomorrow Night Blue</a></li>
            <li><a tabindex="-1" href="#" data-value="tomorrow_night_bright" >Tomorrow Night Bright</a></li>
            <li><a tabindex="-1" href="#" data-value="tomorrow_night_eighties" >Tomorrow Night 80s</a></li>
            <li><a tabindex="-1" href="#" data-value="twilight" >Twilight</a></li>
            <li><a tabindex="-1" href="#" data-value="vibrant_ink" >Vibrant Ink</a></li>
          </ul>
        </div>

        <div class="btn-group">
          {% if name in config['WIKI_LOCKED_PAGES'] %}
            <a class="btn btn-danger btn-sm">
              <i class="fa fa-lock"></i>
              <span class="hidden-xs">Locked</span>
            </a>
          {% else %}
            <a id="submit-btn" class="btn btn-primary btn-sm">
              <i class="fa fa-save"></i>
              <span class="hidden-xs">Save</span>
            </a>
          {% endif %}
        </div>

      </div>
    </div>

    <section class="entry-markdown active">
      <header class="floatingheader" id="entry-markdown-header">
        <small>Markdown</small>
        <a class="markdown-help" href=""><span class="hidden">What is Markdown?</span></a>
      </header>
      <section id="entry-markdown-content" class="entry-markdown-content">
        <div id="editor-{{ name | b64encode }}" data-submitbtn='submit-btn' data-themeselect="theme-list" data-mode="markdown"
             data-preview="preview" class="editor">{{ content }}</div>
      </section>
    </section>

    <section class="entry-preview">
      <header class="floatingheader" id="entry-preview-header">
        <small>Preview</small>
      </header>
      <section class="entry-preview-content">
        <div id="preview"></div>
      </section>
    </section>

  </div>

{% endblock %}

realms/modules/wiki/templates/wiki/history.html
{% extends 'layout.html' %}
{% block body %}

  <h2>History for <strong>{{ name }}</strong></h2>
  <p>
    <a class="btn btn-default btn-sm compare-revisions">Compare Revisions</a>
  </p>

  <table class="table table-bordered revision-tbl dataTable DTTT_selectable">
    <thead>
    <tr>
      <th>Name</th>
      <th>Revision Message</th>
      <th>Date</th>
    </tr>
    </thead>
    <tbody>
    <tr><td colspan="3" style="text-align: center">Loading file history...</td></tr>
    </tbody>
  </table>
  <p>
    <a class="btn btn-default btn-sm compare-revisions">Compare Revisions</a>
  </p>

{% endblock %}

{% block css %}
  <style type="text/css">
    table.dataTable td {
      transition: background-color 0.5s linear, color 0.5s linear;
      transition-delay: 0.1s;
    }
    table.dataTable tr.active td {
      transition: background-color 0.1s linear, color 0.1s linear;
      transition-delay: 0s
    }
    table.dataTable tbody tr:hover {
      background-color: #d8d8d8 !important;
    }
  </style>
{% endblock %}

{% block js %}
  <script>
    $(document).ready(function() {
      var selected = [];
      var selected_pos = [];

      $('.dataTable').dataTable({
        serverSide: true,
        ajax: {
          url: '{{ url_for('.history_data', name=name) }}',
          dataSrc: function (data) {
            $('.dataTable').data('fully_loaded', data.fully_loaded);
            return data.data
          }
        },
        ordering: false,
        bFilter: false,
        columns: [
          {
            "data": null,
            "render": function (data) {
              return '<img src="' + data.gravatar + '?s=20" class="avatar" />&nbsp;&nbsp;' + data.author
            }
          },
          {
            "data": null,
            "render": function (data) {
              return '<a href="' + data.link + '" class="label label-primary">View</a>&nbsp;&nbsp;' + data.message
            }
          },
          { "data": "date" }
        ],
        rowCallback: function( row, data, index ) {
            index += $('.dataTable').DataTable().page.info().start;
            $(row).data('index', index);
            if ( $.inArray(data.DT_RowId, selected) !== -1 ) {
                $(row).addClass('active');
            }
        },
        infoCallback: function( settings, start, end, max, total, pre ) {
          if (!$('.dataTable').data('fully_loaded')) {
            total += "+"
          }
          return "Showing " + start +" to "+ end + " of " + total + " revisions.";
        }
      });

      $('.dataTable tbody').on('click', 'tr', function () {
        var id = this.id;
        var selected_index = $.inArray(id, selected);

        if ( selected_index === -1 ) {
            selected.push( id );
            selected_pos.push( $(this).data('index') );
            if ( selected.length > 2) {
                // Only 2 selected at once
                var shifted = selected.shift();
                selected_pos.shift();
                $('#' + shifted).removeClass('active');
            }
        } else {
            selected.splice( selected_index, 1 );
            selected_pos.splice( selected_index, 1);
        }

        $(this).toggleClass('active');
      });
      $(".compare-revisions").click(function(){
        if (selected.length != 2) return;
        if (selected_pos[1] > selected_pos[0]) {
          selected.reverse()
        }
        revs = selected.join("..");
        location.href = "{{ config.RELATIVE_PATH }}/_compare/{{ name }}/" + revs;
      });
    });
  </script>
{% endblock %}

realms/modules/wiki/templates/wiki/index.html
{% extends 'layout.html' %}

{% block js %}
<script>
$(document).ready(function() {
  $('.data-table').dataTable({'aaSorting': [[0, "asc"], [1, "asc"]]});
});
</script>
{% endblock %}

{% block body %}
  <h2>Index of <a href="{{ url_for('wiki.index') }}">/</a>
    {%- set parts = path.split('/') -%}
    {%- for dir in parts if dir -%}
      <a href="{{ url_for('wiki.index', path='/'.join(parts[:loop.index])) }}">{{ dir }}/</a>
    {%- endfor -%}
  </h2>
  <table class="table table-bordered data-table">
    <thead>
    <tr>
      <th style="width: 1px;"></th>
      <th>Name</th>
      <th class="hidden-xs">Bytes</th>
      <th class="hidden-xs hidden-sm">Created</th>
      <th>Modified</th>
    </tr>
    </thead>
    {% for file in index %}
      <tr>
      {% if file['dir'] %}
        <td><i class="fa fa-folder-open-o"><span style="display:none;">Dir</span></i></td>
        <td><a href="{{ url_for('wiki.index', path=file['name']) }}">{{ file['name'][path|length:] }}</a></td>
      {% else %}
        <td><i class="fa fa-file-text-o"><span style="display:none;">Page</span></i></td>
        <td><a href="{{ url_for('wiki.page', name=file['name']) }}">{{ file['name'][path|length:] }}</a></td>
      {% endif %}
        <td class="hidden-xs">{{ file['size'] }}</td>
        <td>{{ file['ctime']|datetime }}</td>
        <td class="hidden-xs hidden-sm">{{ file['mtime']|datetime }}</td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

realms/modules/wiki/templates/wiki/page.html
{% extends 'layout.html' %}

{% block feed %}
    <link href="{{ url_for('wiki.feed', name=name) }}" rel="feed" type="application/atom+xml" title={{ "Recent changes for page '{}'".format(name) }} >
{% endblock %}

{% block page_menu %}
  <div class="controls pull-right">
    <a class="btn btn-default btn-sm" href="{{ url_for('wiki.edit', name=name) }}">Edit</a>
    <a class="btn btn-default btn-sm" href="{{ url_for('wiki.history', name=name) }}">History</a>
  </div>
{% endblock %}

{% block body %}
  {% if commit %}
    <div id="page-action-bar">
      <form method="POST" action="{{ url_for('wiki.revert') }}" class="ajax-form" data-redirect="{{ url_for('wiki.page', name=name) }}">
        <input type="hidden" value="{{ name }}" name="name" />
        <input type="hidden" value="{{ commit }}" name="commit" />
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/
        <input type="submit" class="btn btn-danger btn-sm" title="Revert back to this revision" value="Revert" />
      </form>
    </div>
  {% endif %}
  <div id="page-content"></div>

{% endblock %}

{% block js %}
  <script>
    $(function(){
      var pageData = {{ page.data|tojson|safe }};
      $("#page-content").html(MDR.convert(pageData, {{ partials|d([])|tojson|safe }})).show();

      var match = pageData.match(/# (.*?)\n/);
      if (match && match[1]) {
        var title = $("title");
        title.text(title.text() + " - " + match[1]);
      }
    });
  </script>
{% endblock %}